### ISSUE TITLE
UKBAP and Red Data Book Species

### ISSUE THREAD

**Issue by joejcollins** [joejcollins/captain-magenta#11]
Have another column(s) for status which could also include Section 41 (aka UKBAP) species and perhaps Red listed species and Schedule 9).

Use the same mechanism as the axiophytes relying on Taxon ID then roll out for other lists in version 2.

Is this in the NBN anyway?

**Comment by DanWrench** [comment]
These lists are already stored on the NBN. We have the ability to add others like the Shropshire list of axiophytes

**Comment by magscousins** [comment]
Would be a useful feature if NBN maintain these lists. Sophie confirmed there would be a way using some kind of look up for Shropshire axiophytes.
